version: "3.9"

services:
  central:
    image: samply/secret-sync-central:latest
    depends_on:
      - proxy
    environment:
      - ALL_PROXY=${HTTPS_PROXY}
      - NO_PROXY=proxy
      - BEAM_URL=http://proxy:8081
      - BEAM_ID=secret-sync-central.${PROXY_ID}
      - BEAM_SECRET=${BEAM_SECRET}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_ID=${KEYCLOAK_ID}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_SECRET=${KEYCLOAK_SECRET}
      - KEYCLOAK_SERVICE_ACCOUNT_ROLES=${KEYCLOAK_SERVICE_ACCOUNT_ROLES}
      - KEYCLOAK_GROUPS_PER_BH=${KEYCLOAK_GROUPS_PER_BH}
      - verbis_GITLAB_URL=${verbis_GITLAB_URL}
      - verbis_GITLAB_API_ACCESS_TOKEN=${verbis_GITLAB_API_ACCESS_TOKEN}
      - verbis_GITLAB_REPO_FORMAT=${verbis_GITLAB_REPO_FORMAT}
      - bbmri_GITLAB_URL=${bbmri_GITLAB_URL}
      - bbmri_GITLAB_API_ACCESS_TOKEN=${bbmri_GITLAB_API_ACCESS_TOKEN}
      - bbmri_GITLAB_REPO_FORMAT=${bbmri_GITLAB_REPO_FORMAT}
      - ICINGA_CONFIG_PATH=/icinga.toml
    volumes:
      - ./icinga.toml:/icinga.toml

  proxy:
    image: samply/beam-proxy:develop
    environment:
      - APP_secret-sync-central_KEY=${BEAM_SECRET}
      - BROKER_URL=${BROKER_URL}
      - PROXY_ID=${PROXY_ID}
      - RUST_LOG=info
    secrets:
      - privkey.pem
      - root.crt.pem

secrets:
  privkey.pem:
    file: ${PRIVKEYFILE}
  root.crt.pem:
    file: ${BROKER_ROOT_CERT}
